### ISSUE TITLE
نسخه ی اولیه ی نیازمندی ها

### ISSUE THREAD

**Issue by mahdialikhasi** [Arash-Mari-Oriyad/tap2tour#1]
نوشتن نسخه ی اولیه ی نیازمندی ها بر اساس فایل پروپوزال آپلود شده در گیت
در این نسخه تنها نیازمندی هایی که در نسخه ی ۱ سیستم قرار است هندل شود مطرح میشود و تنها به صورت عنوان نوشته میشود
(Requirements)
@hangman1998

**Comment by hangman1998** [comment]
نسخه اولیه داکیومنت بارگذاری شد.
