### ISSUE TITLE
registration activity diagram checking

### ISSUE THREAD

**Issue by Arash-Mari-Oriyad** [Arash-Mari-Oriyad/tap2tour#10]
Check registration activity diagram.

**Comment by aalaei** [comment]
بررسی شد و پس از تغییرات کوچک commit شد.

**Comment by aalaei** [comment]
I think these three parts could make this diagram more complete:
-user email verification
-phone number verification
- double password(for getting new password)

**Comment by Arash-Mari-Oriyad** [comment]
done
