### ISSUE TITLE
Use Case Description

### ISSUE THREAD

**Issue by mahdialikhasi** [Arash-Mari-Oriyad/tap2tour#15]
نوشتن use case description های مربوطه 
با توجه به use case diagram رسم شده
این description ها باید طبق فرمت مطرح شده در مرجع درس نوشته شود
@mahdialikhasi 
@hangman1998

**Comment by mahdialikhasi** [comment]
لطفا با توجه به تقسیم کار نوشته شده موارد مطرح شده در گیت آپلود گردد

**Comment by mahdialikhasi** [comment]
نوشتن 
Profile Management use case description
@mahdialikhasi

**Comment by mahdialikhasi** [comment]
نوشتن 
Tour Management use case description
@mahdialikhasi

**Comment by hangman1998** [comment]
textbook's  use case description template:
(you're most welcome !)
http://bcs.wiley.com/he-bcs/Books?action=resource&bcsId=9422&itemId=1118804678&resourceId=37519
