### ISSUE TITLE
Sequential Model

### ISSUE THREAD

**Issue by mahdialikhasi** [Arash-Mari-Oriyad/tap2tour#17]
افزودن 
Seq. Models
بر اساس کلاس دیاگرام و اکتیویتی دیاگرام

**Comment by mahdialikhasi** [comment]
انجام قسمت
Tour Management
توسط 
@Arash-Mari-Oriyad 
@mahdialikhasi

**Comment by mahdialikhasi** [comment]
انجام قسمت های 
login, logout
@aalaei

**Comment by mahdialikhasi** [comment]
انجام قسمت 
view, search. filter
@aalaei

**Comment by aalaei** [comment]
دوستان قسمت search filter , rating انجام شد بررسی کنید.

**Comment by aalaei** [comment]
بچه ها login و logout هم آماده چک کردنه
