### ISSUE TITLE
Business modeling

### ISSUE THREAD

**Issue by mahdialikhasi** [Arash-Mari-Oriyad/tap2tour#2]
طراحی، مکتوب سازی و آپلود فایل مربوط به  Business modelling بر اساس پروپوزال و فایل requirement آپلود شده در سیستم
در این فایل اجزا سیستم و داده ها و اطلاعات مربوط به هر قسمت به طور دقیق تر بررسی شده و مکتوب سازی میشود
@hangman1998 
@aalaei

**Comment by hangman1998** [comment]
first draft was uploaded by @aalaei
