### ISSUE TITLE
بررسی نسخه اولیه requirements

### ISSUE THREAD

**Issue by hangman1998** [Arash-Mari-Oriyad/tap2tour#3]
first draft was uploaded.
please review and complete it.
also non-functional part could be organized better.
for an idea of how to disassemble the non-functional into multiple parts please review the course textbook on page 108 (figure 3.1).

**Comment by mahdialikhasi** [comment]
بازبینی منورد نظر انجام شد و موارد زیر اصلاح گردید
- جداسازی مشاهده نظرات و گالری تور از قسمت ثبت نام در تور و ایجاد قسمت مشاهده ی مشخصات تور

- اضافه کردن قسمت رای دهی به تور

- حذف مولتی مدیا و مقاله از مشخصات تور

- افزودن قسمت ویرایش و حذف تور
