### ISSUE TITLE
business modeling review

### ISSUE THREAD

**Issue by hangman1998** [Arash-Mari-Oriyad/tap2tour#4]
please someone check that this document is according to the standards.
and also that it is answers all of the requirements asked in the requirement document.

**Comment by mahdialikhasi** [comment]
بیزینش مدلینگ مورد نظر بررسی شد و تغییرات لازمه اعلام شد
تغییرات :
- کاهش اطلاعات مورد نیاز برای ثبت نام

- حذف تکرار های بیهوده و اشکالات گرامری

- ویرایش قسمت پیش نویس در ایجاد تور

- افزودن ذخیره به عنوان پیش نویس در ویرایش تور
نهایتا خروجی pdf ایجاد و ذخیره شد
