### ISSUE TITLE
use case diagram

### ISSUE THREAD

**Issue by mahdialikhasi** [Arash-Mari-Oriyad/tap2tour#5]
آپلود فایل مربوط به use case diagram
این فایل تحت draw.io ایجاد باید شود و در آن قرار است که به نحوه ی تعامل کاربران با سیستم به صورت شماتیک اشاره گردد
همچنین روابط include و exclude برای قسمت های مختلف سیستم که در requirement ذکر شده است باید در نظر گرفته شود
@hangman1998

**Comment by hangman1998** [comment]
uploading the version that was created in the lab back in the Tuesday.

**Comment by hangman1998** [comment]
uploaded second draft of use case diagram.
please note the following before reviewing the document:
* association relations between actors and use cases don't follow the rules ( all of them are two sided which may not be the case all the time . and also they don't have the indicators of how many to many is a specific relation.)

* please read the part about use cases in the course text book before applying any updates.

**Comment by mahdialikhasi** [comment]
بازنگری انجام شد و تغییرات زیر انجام گردید
- اضافه کردن EXTEND به پروفایل کاربری

- حذف EXTEND مشکل مالی از پروفایل کاربری

- تغییر متن EXTEND و INCLUDE به فرمت کتاب
