### ISSUE TITLE
tour management review 

### ISSUE THREAD

**Issue by aalaei** [Arash-Mari-Oriyad/tap2tour#9]
یکی از دوستان زحمت چک کردن این اکتیویتی دیاگرام رو بکشه

**Comment by Arash-Mari-Oriyad** [comment]
تاریخ و نوع تور ها به ویژگی های یک تور اضافه شود

**Comment by Arash-Mari-Oriyad** [comment]
در این دیاگرام از 
tour profile
استفاده شود

**Comment by aalaei** [comment]
با تشکر از وقتی که برای بررسی گذاشتید
